### ISSUE TITLE
Any samples on using this within a HAPI route handler? 

### ISSUE THREAD

**Issue by jgrenon** [hapijs/faketoe#31]
Could you provide a small sample on how we can use this inside a HAPI server route handler?

**Comment by mtharrison** [comment]
Faketoe can be piped a stream, so you could just give it the hapi `request.payload` object, if you set the hapi payload output to `stream`:

```javascript
server.route({
    config: {
        payload: {
            parse: false,
            output: 'stream'
        }
    },
    method: 'POST',
    path: '/',
    handler: function (request, reply) {

        var parser = Faketoe.createParser(function (err, result) {

            if (!err) {
                reply(result);
            }
        });
        request.payload.pipe(parser);
    }
});
```

The above just spits the parsed data back at you as JSON:

```
curl -X POST localhost:4000 -H "Content-type: application/xml" -d "<?xml version=\"1.0\" encoding=\"UTF-8\" ?><reasons><i><love><xml>0</xml></love></i></reasons>"

{"reasons":{"i":{"love":{"xml":"0"}}}}
```

**Comment by jgrenon** [comment]
In the case of large documents, is it possible not to accumulate the 
produced JSON to memory? Can we just handle on('endElement') events 
without providing a callback for the final result?

I may receive very large inventory details in XML (thousands of products 
+ quantity) from thousands of stores... Would be nice to parse those 
files one element at the time as the full document is quite meaningless 
in my use case.

Can Faketoe handle this? If not, can I help in creating this stateless 
version?

**Comment by nlf** [comment]
faketoe is intended specifically to build a full document. if you just want events you should probably use `node-expat` directly
